# Generated by Django 3.1.4 on 2021-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QtsAnsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('question', models.CharField(max_length=250, null=True)),
                ('opt1', models.CharField(max_length=250, null=True)),
                ('opt2', models.CharField(max_length=250, null=True)),
                ('opt3', models.CharField(max_length=250, null=True)),
                ('opt4', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
